sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputCustomDeclarationOrderCheckGettersSetters.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputCustomDeclarationOrderCheckMainMethod.java

- Added tests to increase coverage
- Fixed rule in test method
- Fixed formatting (indents)
Pull #295

Improved CustomDeclarationOrderCheck

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputOverridableMethodInConstructor10.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputOverridableMethodInConstructor13.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputOverridableMethodInConstructor17.java

- Added more test cases (examples)
- Replaced to Serializable/Clonable stirngs to Cloneable.class.getSimpleName()
- Increase coverage by using true and false values of checkCloneMethod and checkReadObjectMethod
Pull #318

Increase OverridableMethodInConstructorCheck code coverage:

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheck.java

All violations of rule [Short-circuit logic should be used in boolean contexts](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS2178) are fixed.

Short-circuit logic is used in boolean expressions, issue #169

---

README.textile

I am proposing a small update to the list of 'related projects' in the README:
- Mention the Gradle Checkstyle plugin (on the grounds that the Maven Plugin was mentioned as well, and Gradle is increasingly popular)
- Correct the link to the SonarQube Checkstyle plugin
- Change the order of entries so that related projects are grouped together
In addition to that, I would like to ask you to accept the fourth change, which is including a reference to [Checkstyle Addons](http://checkstyle-addons.thomasjensen.com/), a small collection of additional checks that I am the author of - it's free and open source.
Thanks for your support!

Changes to 'Related Projects' section in README.textile

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/WhitespaceBeforeArrayInitializerCheck.java
sevntu-checks/src/main/resources/com/github/sevntu/checkstyle/checks/coding/messages.properties
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/WhitespaceBeforeArrayInitializerCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputWhitespaceBeforeArrayIntializer.java

Introduces new WhitespaceBeforeArrayInitializerCheck. When we deal with Array Initializer we have to deal with two situations:
a) int ints[] = {1, 2, 3, 4};
b) new int[] {1,2,3,4}
In first situation we have to check where lays the parent of Array Initializer(Assignment) , in second we have to check previous sibling (Array Declarator int[]).

Introducing WhitespaceBeforeArrayInitializerCheck, fixing issue #333

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/DiamondOperatorForVariableDefinitionCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/DiamondOperatorForVariableDefinitionCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputDiamondOperatorForVariableDefinitionCheck.java
sevntu-checks/suppressions.xml

Issue #430: Fix false positive in DiamondOperatorForVariableDefinitionCheck

---

sevntu-checks/CheckstyleFormatterForEclipse.xml

Done on Eclipse Luna SR 2 on Windows.
I imported the original, went through a few files and played around with the settings to get them close to how CS is currently formatted.
Not sure if we want to validate this somehow...
Eclipse doesn't save the file in the same order, so I created a small program to re-sort it based on the original XML sorting.

minor: updated eclipse formatter to checkstyle current standards

---

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/naming/checkstyle-metadata.properties
eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/naming/checkstyle-metadata.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/package-info.java
sevntu-checks/src/main/resources/com/github/sevntu/checkstyle/checks/naming/messages.properties
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/naming/InputUniformEnumConstantNameCheck.java
sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml

Removed logic to distinguish enum objects from enum constants.
Added support for multiple format of enum values. Enum is allowed if there is at least one format, that hist values conform.
Default formats are both CamelCase and UPPER_CASE
Check for guava
formats value | Number of violations found
------------- | -------------
default | 0
"^[A-Z][a-zA-Z0-9]*$" (CamelCase) | 59
"^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$" (UPPER_CASE) | 12
Reports:
http://pbaranchikov.github.io/checkstyle/enum-value-uppercase/checkstyle.html
http://pbaranchikov.github.io/checkstyle/enum-value-camel/checkstyle.html

Implemented UniformEnumConstantNameCheck

---

sevntu-checks/.classpath

The latest m2e (Maven support for Eclipse) creates the .classpath file
like this.  It's a PITA that it always shows up as "dirty" in Git, and
it would thus be best to merge this to avoid that.
An alternative could be to not keep Eclipse metadata in Git at all
anymore.
Change-Id: I91d4417183fa6d5a9db2b4fa4049b1e0fbfef04f
Signed-off-by: Michael Vorburger <vorburger@redhat.com>

.classpath with minor additions, as per M2E

---

sevntu-checks/.classpath
sevntu-checks/CheckstyleFormatterForEclipse.xml
sevntu-checks/pom.xml

Eclipse was giving a minor version mismatch. It was because we have some parts that specifically still reference Java 7.

minor: changed java 7 compile to java 8

---

sevntu-checks/sevntu-checks.xml
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/AllChecksTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java
sevntu-checks/suppressions.xml

Issue #506
Unit test added. It will fail for now as configs aren't added.
The following are the missing configs:
````
<module name="com.github.sevntu.checkstyle.checks.annotation.ForbidAnnotation"/>
<module name="com.github.sevntu.checkstyle.checks.coding.EmptyPublicCtorInClass"/>
<module name="com.github.sevntu.checkstyle.checks.coding.DiamondOperatorForVariableDefinition"/>
<module name="com.github.sevntu.checkstyle.checks.design.InnerClass"/>
<module name="com.github.sevntu.checkstyle.checks.design.HideUtilityClassConstructor"/>
<module name="com.github.sevntu.checkstyle.checks.annotation.RequiredParameterForAnnotation"/>
<module name="com.github.sevntu.checkstyle.checks.coding.NameConventionForJunit4TestClasses"/>
<module name="com.github.sevntu.checkstyle.checks.coding.UselessSuperCto …
```

Issue #506: added unit test to verify checks referenced in config

---

.travis.yml

Issue #451: reworked travis and added PR desc testing

---

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.xml
sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ReturnCountExtendedCheck.java
sevntu-checks/src/main/resources/com/github/sevntu/checkstyle/checks/coding/messages.properties
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ReturnCountExtendedCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputReturnCountExtendedCheckAnonymousClasses.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputReturnCountExtendedCheckLambdas.java

Issue #463
Lambdas are now supported.
Also 100% code coverage. [Regression ](http://rveach.no-ip.org/checkstyle/regression/reports/120/) showed no NPEs.
````
<module name="ReturnCountExtendedCheck">
<property name="maxReturnCount" value="1"/>
<property name="ignoreMethodLinesCount" value="0"/>
<property name="minIgnoreReturnDepth" value="99"/>
<property name="ignoreEmptyReturns" value="false"/>
<property name="topLinesToIgnoreCount" value="0"/>
</module>
````
One thing to note, lambdas don't have a method name, so the violation message currently prints that as `null`. Should we drop that part of the message? Should we drop support for matching these patterns?

Issue #463: extended ReturnCountExtendedCheck to accept lambdas

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/annotation/InputForbidAnnotation2.java

Issue #520 
`InputForbidAnnotation2.java` was changed to bring back the spirit of what the test was about, which originally had a full classpath annotation in it. See https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/54#issue-7286166 .

Issue #520: 100% coverage for ForbidAnnotationCheck

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ConfusingConditionCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ConfusingConditionCheckTest.java

Issue #520 
`else if (detailAST.getType() == TokenTypes.LITERAL_IF) {` was removed because we are only looking at 2 types of tokens, `if` and `else`. If it isn't one, it must be the other.

Issue #520: 100% coverage for ConfusingConditionCheck

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheckTest.java

Issue #520
`firstOperand.branchContains(constantType)` is removed because `constantType` gets its value from `firstOperand` at `final int constantType = firstOperand.getType();`, so it will always return true.
Regression showed no differences. http://rveach.no-ip.org/checkstyle/regression/reports/131/

Issue #520: 100% coverage for AvoidConstantAsFirstOperandInCondition

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputUnnecessaryParenthesesUbv.java

Issue #520
I was able to achieve coverage for one spot, but the other 2 I couldn't achieve. Regression showed no differences when removed. http://rveach.no-ip.org/checkstyle/regression/reports/139/
` && (next.getType() == TokenTypes.RPAREN);` is not reachable because when we have the open parenthesis, we are guaranteed to have the close one.
I believe the same is true for `exprSurrounded` and we are already checking if they are surrounded else where.

Issue #520: 100% coverage for UnnecessaryParenthesesExtendedCheck

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ConfusingConditionCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ConfusingConditionCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputConfusingConditionCheck.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputConfusingConditionCheck2.java

Issue #454
Fixed NPE in `getAmounOfCodeRowsInBlock`.
Since the method is counting for `blocks` I set the return to 0 if there is no block. Please let me know if we should count lines even if there is no block.

Issue #454: fixed NPE in ConfusingConditionCheck

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java

Issue #520
Identifiers and annotations always have an identifier, so code was removed.

Issue #520: 100% coverage for ForbidWildcardAsReturnTypeCheck

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NoMainMethodInAbstractClassCheck.java

Issue #520 
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/140/
No differences reported.
All removals are null protections that I couldn't hit.
`hasAbstractModifier` and `isMainMethodModifiers` always has modifiers.
`getIdentifier` cases that hit it always have the identifier as this is only checking abstract classes.
`isVoidType` methods always have a type.

Issue #520: 100% coverage for NoMainMethodInAbstractClassCheck

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java

Issue #520 
Couldn't satisfy the missing coverage. There is already null protections above, so it could be related to that.
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/148/
No differences.

Issue #520: 100% coverage for IllegalCatchExtendedCheck

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputSimpleAccessorNameNotation.java

Issue #520
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/159/
Regression for this check is almost useless because we are looking for methods with specific names. I had to disable those checks to get better results and I still couldn't appease some of the coverage spots.
I did however manage to add a lot more tests than was before.

Issue #520: 100% coverage for SimpleAccessorNameNotationCheck

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputForbidCertainImportsSinglePackage.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputForbidsCertainImports.java

Issue #520 and #552
Coverage is now 100%. Added some new tests, including one in issue #552.
`getForbiddenImportsExcludesRegexp` was removed as we never use it.
Some conditions were moved from `visit` to other method `isImportForbidden` since it is common there.
`if (parentDotAST != null) {` was removed because we either always have DOT or IDENT as first token.
`getDefaultTokens` was changed for other issue.
Only other change was `(forbiddenImportsExcludesRegexp == null  || !forbiddenImportsExcludesRegexp.matcher(importText).matches());` to make sure no NPE on a null exclude.

Issue #520 and #552 on ForbidCertainImportsCheck

---

.travis.yml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ConstructorWithoutParamsCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ConstructorWithoutParamsCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckstyleRegressionTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputConstructorWithoutParamsCheck.java

Issue #550
Idea is:
New test will scan checkstyle's sevntu config and add missing checks on the fly, especially new ones from PR.
Will run checkstyle on checkstyle project and expect no violations.
Future enhancements could include ability to specify non-default configuration of checks.
Could be made as a groovy script, but will have to be able to tell what checks are available.

Issue #550: added dynamic checkstyle regression

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheck.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputChildBlockLengthCheck.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputChildBlockLengthCheckDoubleNested.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputChildBlockLengthCheckManyBlocksOnOneScope.java

Issue #520 
Added tests for some cases I found in regression.
`while (curNode != null) {` and `while ((curNode != null) && `
They can't be `null` because we are in a block and are guaranteed some type of end.
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/150/
No differences.

Issue #520: 100% coverage for ChildBlockLengthCheck

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidNotShortCircuitOperatorsForBooleanCheck.java

Issue #559 
I am looking for object blocks over catch block incase `&` is used in a type parameter of an anonymous class.
Regression will show if there are any cases.

Issue #559: ignore object blocks for ShortCircuitOperator check

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputForbidWildcardAsReturnTypeCheck.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputForbidWildcardAsReturnTypeCheckQualifiedAnnotation.java

Issue #575
Removed `hasAnnotation` for Checkstyle's `AnnotationUtility.containsAnnotation`.
Changed the code to examine fully qualified annotations. Changed existing test to pass code coverage for the new fully qualified annotation check.

Issue #575: fixed NPE in ForbidWildcardAsReturnTypeCheck

---

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.properties
eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.xml
sevntu-checks/sevntu-checks.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ConfusingConditionCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MoveVariableInsideIfCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java
sevntu-checks/src/main/resources/com/github/sevntu/checkstyle/checks/coding/messages.properties
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/MoveVariableInsideIfCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckstyleRegressionTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CommitValidationTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputMoveVariableInsideIfCheckFalsePositives.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputMoveVariableInsideIfCheckNoViolations.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputMoveVariableInsideIfCheckViolations.java
sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml

Adding check `MoveVariableInsideIfCheck`.
Also added cases that can cause false positives.
Will rename commit and provide regression.
Fixes in Checkstyle: https://github.com/checkstyle/checkstyle/pull/4328
There was a small bug in my original implementation, so there may be more violations in Checkstyle than before.

Pull #565: added new check MoveVariableInsideIfCheck

---

eclipse-pom.xml
eclipsecs-sevntu-plugin-feature/pom.xml
eclipsecs-sevntu-plugin/pom.xml
sevntu-checks/pom.xml
sevntu-checkstyle-idea-extension/pom.xml
sevntu-checkstyle-maven-plugin/pom.xml
sevntu-checkstyle-sonar-plugin/pom.xml
update-site/pom.xml

Issue #165
I avoided changes in eclipse related projects so "sevntu.checkstyle" will stay there, it is not required to follow maven rules for naming.
@rnveach , please review.
I did not tested all projects, most likely smth will fail, but could be fixed later, demand for maven central is higher.

Issue #165: change groupId to 'com.github.sevntu-checkstyle'

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/CauseParameterInExceptionCheck.java

Issue #589
Moved field reset to `beginTree`.

Issue #589: fixed OutOfBoundsException in CauseParameterInException

---

sevntu-checks/pom.xml

These are changes needed for no error testing from main checkstyle project as talked about at https://github.com/checkstyle/checkstyle/issues/4387#issuecomment-305205047 .
We could already override the checkstyle version number, but the configuration is based on that version number. If CS version is switched to a SNAPSHOT, it will try to load that from github but SNAPSHOT configurations don't exist there. Instead with new changes, wercker will override and give it the PR's configuration location.
One Question, will this be no exception testing (not using `launch.groovy`) or no error testing?
No error testing would be more thorough, and thats what it should be with current changes.
No exception testing would require us to be able to override `failOnViolation` to turn it off, which would be …

config: allowed overriding checkstyle configuration for snapshots

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NestedSwitchCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/NestedSwitchCheckTest.java

Fix for checkstyle/checkstyle#4767 .
We are removing deprecated classes in next release, so we need this class to extend `AbstractCheck` directly.
Will rename commit once I get a PR number.

Pull #: removed excess hierarchy from NestedSwitchCheck

---

index.html

Updates jQuery from the ancient 1.3.2 version to the latest one. I've also replace a jQuery hover effect with a CSS version.
Another change is that _all_ resources are loaded via HTTPS. (This was an issue with the current version: Chrome for example blocks jQuery (loaded via HTTP) when opening the site via HTTPS.)
I've also changed to DocType from XHTML 1.0 to HTML 5.

ghpages: update jquery

---

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/ChecksTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/SevntuXmlUtil.java

Issue #630 
Removed some duplicated utils from checkstyle.
Renaming of `CheckUtil` will have to wait until a new checkstyle release as there are some changes I need to make in checkstyle to make this util more globally acceptable.

Issue #630: use checkstyle's utils instead of copying them

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/HideUtilityClassConstructorCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java

Issue #669: removed branchContains for modifiers

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ConstructorWithoutParamsCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidConstantAsFirstOperandInConditionCheck.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputPublicReferenceToPrivateTypeCheck20.java

Issue #669: removed branchContains for complicated cases (part 1)

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCCommentsInMethodsCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCCommentsInMethodsCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputForbidCCommentsInMethodsCheck.java

Issue #662 
I rewrote the check to use `visitToken` and log on the AST instead of relying on `getFileContents()`.
Tests show no differences. I will confirm the same with regression.

Issue #662: moved ForbidCCommentsInMethodsCheck to log AST

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputOverridableMethodInConstructorCheck28.java

Issue #572 
Added fix to prevent infinite loop.
Will provide limited difference regression and no exception report.

Issue #572: fixed infinite loop in OverridableMethodInConstructorCheck

---

sevntu-checks/pom.xml

There is no eclipse-cs version 8.10 .
This value needs to be fixed as it is a requirement for the release process (old and new) to be able to test in eclipse-cs.
I realize this slightly contradicts https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/705 , but it is not going to be fixed this release, so we should continue with what works for now.

config: fixed incorrect eclipse-cs version

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputForbidCertainMethodCheck.java

https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/721
ForbidCertainMethodCheck allows the number of parameters to be used to
specify forbidden methods more precisely than using only their name;
however it counds those parameters by counting EXPR tokens. Lambdas
appear as LAMBDA tokens, not EXPR tokens, so they aren’t counted
towards the real argument count, resulting in false-positives or
false-negatives depending on the test being run.
This patch changes the argument count to count commas instead, all at
the same level just under the ELIST. This ensures that arguments are
counted regardless of their token type.
Signed-off-by: Stephen Kitt <skitt@redhat.com>

Handle lambdas in ForbidCertainMethodCheck

---

.travis.yml

fix: https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/546264730
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2019-05-02
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

ci: update Travis to openjdk8, as oraclejdk8 is not accessible anymore

---

.ci/travis.sh

Fix regression to remove hardcoded values and rely on values defined in our POM. If these values were ever out of synch, checkstyle regression would not use PR version of sevntu and fall back on released version.
This is why we had the failure at https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/549161973 after the PR was merged. 1.34.1 was released and hardcoded values were not updated.

config: remove hardcoded values for checkstyle regression

---

sevntu-checkstyle-sonar-plugin/pom.xml

Issue #746
Checkstyle dependency was explicitly excluded from the sevntu-sonar plugin.
Tested with the following:
- sonarqube 7.8
- sevntu-checks and checkstyle checks are activated in sonarqube quality profile
- analysis is launched on checkstyle sources with `mvn sonar:sonar -Dsonar.host.url=http://localhost:9000/`
| Checkstyle sonar plugin version | Checkstyle version | Analysis status |
| ------------------------------------------ | -------------------------- | -------------------- |
| 4.17 | 8.17 | Failed with exception |
| 4.18 | 8.18 | Passed |
| 4.19 | 8.19 | Passed |
| 4.20 | 8.20 | Passed |
| 4.21 | 8.21 | Failed with exception |

Issue #746: exclude checkstyle dependency from resulted jar of sevntu-checkstyle-sonar-plugin

---

sevntu-checkstyle-sonar-plugin/pom.xml

Issue #440 
Both dependencies, guava and maven shade plugin, were removed from sevntu sonar plugin.
Tested with the following:
- sevntu-checks and checkstyle checks are activated in sonarqube quality profile
- analysis is launched on checkstyle sources with `mvn sonar:sonar -Dsonar.host.url=http://localhost:9000/`
| Sonarqube version | Checkstyle sonar plugin version | Checkstyle version | Analysis status |
| ------------------------- | ------------------------------------------ | -------------------------- | -------------------- |
| 7.5 | 4.17 | 8.17 | Passed |
| 7.8 | 4.18 | 8.18 | Passed |
| 7.8 | 4.19 | 8.19 | Passed |
| 7.8 | 4.20 | 8.20 | Passed |
Jar content before removal:
```
$ zipinfo target/sevntu-checkstyle-sonar-plugin-1.34.1.jar | grep 'lib/.*jar'
-rw----     2.0 fat …
```

Issue #440: remove guava and shade plugin dependencies

---

sevntu-checks/pom.xml
sevntu-checkstyle-sonar-plugin/pom.xml

Issue #758.
Checkstyle dependency was marked as provided in sevntu-checks module. Redundant exclusion was removed from sevntu-sonar plugin.
See comments about checking other extensions: [sevntu-checkstyle-idea-extension](https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/758#issuecomment-509392019), [sevntu-checkstyle-maven-plugin](https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/758#issuecomment-509404538), [eclipsecs-sevntu-plugin](https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/758#issuecomment-509401382).

Issue #758: make checkstyle dependency as provided in sevntu-checks

---

index.html
wercker.yml

Issue #766 
- `sevntu-checkstyle-maven-plugin` removed
- dummy wercker config was added to fix ci failure

Issue #766: remove sevntu-checkstyle-maven-plugin

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java

```
[ERROR] src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java:[169,15] (coding) UnnecessarySemicolonInEnumeration: Unnecessary semicolon
```

minor: Fix UnnecessarySemicolonInEnumeration violation

---

sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputReturnCountExtendedCheckMethodsInMethods.java

Although the specification allows multiple names per `@author` tag, it is better to have only one name per tag to avoid ambiguities.

doc: fix javadoc in InputReturnCountExtendedCheckMethodsInMethods.java

---

sevntu-checks/.ci/eclipse-compiler-javac.sh
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/ChecksTest.java
sevntu-checkstyle-sonar-plugin/import-control-test.xml
sevntu-checkstyle-sonar-plugin/pom.xml
sevntu-checkstyle-sonar-plugin/src/main/java/com/github/sevntu/checkstyle/sonar/CheckstyleExtensionRulesDefinition.java
sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml
sevntu-checkstyle-sonar-plugin/src/test/java/com/github/sevntu/checkstyle/sonar/CheckstyleExtensionPluginTest.java
sevntu-checkstyle-sonar-plugin/src/test/java/com/github/sevntu/checkstyle/sonar/CheckstyleExtensionRulesDefinitionTest.java
sevntu-checkstyle-sonar-plugin/suppressions.xml

Issue #763
- Plugin was updated to use sonar-plugin-api 7.9 as a provided dependency.
- Plugin code was updated to adhere new api.
- UTs were introduced.
**Notes:**
1. Plugin doesn't work on sonarqube < 7.9 and gives the following error when trying to use it with sonarqube version < 7.9 which is expected. This update breaks compatibility with old sonar versions.
```
ERROR web[][o.s.s.p.Platform] Web server startup failed: Plugin SevNTU Checkstyle Sonar Extension Plugin [sevntucheckstyle] requires at least SonarQube 7.9
```
2. Plugin was tested with **checkstyle-sonar-plugin-4.27** and **sonarqube-7.9.2** in the following way, works fine:
2.1. Create new java quality profile with all checkstyle checks including sevntu checks.
2.2. Mark the profile as default.
2.3. Launch `mvn sonar:sonar …

Issue #763: upgrade sonar-plugin-api to 7.9

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java

Issue #793
Usages of `node.getNumberOfChildren() > 0` replaced with `node.getFirstChild() != null`.
This is less readable, may be there should be method
```java
default boolean hasChildren() {
return firstChild != null;
}
```
in the DetailAst interface?

Remove usages of DetailAST::getNumberOfChildren

---

sevntu-checks/pom.xml

Checkstyle is looking to remove some deprecated methods and CI noticed that you are not on the latest maven-checkstyle-plugin which is still using some deprecated methods. 
Issue: checkstyle/checkstyle/issues/7190
PR: checkstyle/checkstyle#7778

config: upgrade maven-checkstyle-plugin to 3.1.1

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/RequiredParameterForAnnotationCheck.java

Fixed a violation caused in `RequiredParameterForAnnotationCheck` caused by the new check MissingLeadingAsteriskCheck
As discussed in the comments of [checkstyle/checkstyle#8085](https://github.com/checkstyle/checkstyle/pull/8085).

minor: fix violation for MissingLeadingAsterisk

---

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/EitherLogOrThrowCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/NoMainMethodInAbstractClassCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/AllChecksTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java

According to https://checkstyle.sourceforge.io/config_javadoc.html#JavadocParagraph
> There is one blank line between each of two paragraphs and one blank line before the at-clauses block if it is present.
Unfortunately, this check is not working yet in checkstyle, so many of these violations sneaked into the repository, but it's coming in https://github.com/checkstyle/checkstyle/pull/7932 .
I wrote a script to apply the missing newline violations from mvn verify. It is available here: https://github.com/josephmate/FixAtClauseError

minor: fix violations from RequireEmptyLineBeforeAtClauseBlock

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck8.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck9.java

Issue #817: Support static wildcard import of junit's fail method in RequireFailForTryCatchInJUnitCheck

---

.travis.yml

https://travis-ci.org/github/sevntu-checkstyle/sevntu.checkstyle/jobs/759133754#L877

config: bump sonar runtime to jdk11 as it demands now as minimal version

---

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ConfusingConditionCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/NameConventionForJunit4TestClassesCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/SingleBreakOrContinueCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/TernaryPerExpressionCountCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/AvoidConditionInversionCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/CauseParameterInExceptionCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/HideUtilityClassConstructorCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/NestedSwitchCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheckTest.java
sevntu-checks/suppressions.xml

Identified at https://github.com/checkstyle/checkstyle/pull/8177#issuecomment-782748438 ,
Suppressions were hiding too much in tests. They were removed and only javadoc issues were fixed.

minor: fix handling of checkstyle checks for tests

---

sevntu-checks/.ci/wercker.sh

infra: move wercker no-exception testing to diff.groovy
Right now, this PR is only a test to make sure that combined diff/launch .groovy will work as intended for no-exceptions testing.  Once PR for https://github.com/checkstyle/contribution/issues/529 is merged, we can change the repo in `checkout-from` back to checkstyle's contribution repo and review this PR.

infra: move wercker no-exception testing to diff.groovy

---

sevntu-checks/suppressions.xml

As discussed from https://github.com/checkstyle/checkstyle/pull/9909#discussion_r628893136
The id value "noUsageOfGetFileContents()Method" should get rid of () to be selectable by double click.

minor: make id value selectable

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidNotShortCircuitOperatorsForBooleanCheckBitwiseAfterArray.java

Related to https://github.com/checkstyle/checkstyle/pull/9922,  before we update sevntu check's `checkstyle.eclipse-cs.version` to 8.43, we will need to merge this PR to avoid regression in `AvoidNotShortCircuitOperatorsForBooleanCheck` and `NoNullForCollectionReturnCheck`.
Diff report from checkstyle#9922: https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/24f673f_2021192452/reports/diff/index.html (regression)
Diff report after this PR: https://nmancus1.github.io/sevntu-diff-3145-b/index.html (no regression)

minor: update checks (related to checkstyle #3145)

---

sevntu-checks/pmd-main.xml
sevntu-checks/pmd-test.xml
sevntu-checks/pmd.xml
sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ConfusingConditionCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/Jsr305AnnotationsCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NoMainMethodInAbstractClassCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/AllChecksTest.java

Issue #849
Update PMD to the most recent version.
Regression report (to be extra sure): https://pbludov.github.io/issue-849-pmd-6.35/

Issue #849: bump pmd to version 8.35

---

sevntu-checks/pom.xml
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/Jsr305AnnotationsCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/PreferMethodReferenceCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NoMainMethodInAbstractClassCheck.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/Jsr305AnnotationsCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheckTest.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheckTest.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputNoNullForCollectionReturnCheckObjectArray.java
sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputForbidWildcardAsReturnTypeCheckNewArrayStructure.java

Related to https://github.com/checkstyle/checkstyle/pull/10104
https://nmancus1.github.io/issue-10100_check_diff_reports_2021_06_11/diff_sevntu-check-regression_part_1/index.html
`NoMainMethodInAbstractClassCheck`- new NPE
`ForbidWildcardAsReturnType` - lots of new legit violations, we were missing violations on methods like `public Class<?>[] getClasses() {}`
`InnerClass` - symmetrical column changes
`StaticMethodCandidate` - new violations, we were missing violations previously on methods with `String` return type
-----------------------
https://nmancus1.github.io/issue-10100_check_diff_reports_2021_06_11/diff_sevntu-check-regression_part_2/index.html
`MoveVariableInsideIf` - symmetrical column number changes
`SimpleAccessorNameNotation` - symmetrical column number changes …

minor: update checks(related to checkstyle issue#10100)

---

eclipsecs-sevntu-plugin-feature/feature.xml

Fix the URLs that should have used `.io` instead of `.com`.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/857#issuecomment-903161782

minor: fix broken URLs

---

update-site/index.html

Updated gh-pages site so there is a main page for index and not be confused with the wrong URL.
I think CI can be ignored since there is no setup for it on gh-pages.

Issue #857: added main index to update site

---

.travis.yml
sevntu-checks/.ci/eclipse-compiler-javac.sh
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java

Same changes as for the upstream. With a couple of additions.

infra: use latest ecj compiler in ci

---

.ci/travis.sh
.travis.yml

Travis allow unlimited execution only on special arch
https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z
s390x: no jdk11 support, only jre (problmes with jacoco, javadoc), jdk8 support is problematic.
Question to support: https://travis-ci.community/t/arch-s390x-has-jre-but-most-builds-of-java-needs-jdk/12143/2

infra: use free arch in Travis to avoid usage of credits

---

.travis.yml

https://app.travis-ci.com/github/sevntu-checkstyle/sevntu.checkstyle/jobs/538683265#L809
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar 
(attach-javadocs) on project sevntu-checks: MavenReportException: 
Error while generating Javadoc: Unable to find javadoc command: 
The environment variable JAVA_HOME is not correctly set. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: 
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) 
on project sevntu-checks: MavenReportException: Error while generating Javadoc: 
Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set.
```

infra: setup JAVA_HOME

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java
sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java

Related to changes at https://github.com/checkstyle/checkstyle/pull/10839/commits/7462b00c2f0d470be6d3d8825f83c717cc5696aa, and noticed in check regression testing for https://github.com/checkstyle/checkstyle/pull/10979, we need to replace usages of `CheckUtil#createFullType` with `FullIdent#createFullIdent` now that `CheckUtil#createFullType` has been removed.
It breaking compatibility with main library.
New versions of sevntu can not work with checkstyle versions below 9.2 due to https://github.com/checkstyle/checkstyle/issues/10144

Replace usage of CheckUtil#createFullType with FullIdent#createFullIdent

---

.github/dependabot.yml

Only adding 1 folder for now. Set for weekly, max 2 PRs.
After the first set of PRs, we can probably switch it to monthly with a bit higher PR count.

config: adds dependabot for sevntu checks

---

sevntu-checks/pom.xml

This resolves a spam of warnings when running the suite and my be related to the java 11 upgrade:
````
[WARNING] javadoc: warning - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
````

dependency: upgrades maven-javadoc-plugin to 3.4.1

---

sevntu-checks/ant-phase-verify-sevntu.xml
sevntu-checks/ant-phase-verify.xml

The [Ant manual Property Task](http://ant.apache.org/manual/Tasks/property.html) states:
>    Properties are immutable: whoever sets a property first freezes it for the rest of the build; they are most definitely not variables.
I created a intermediator variable to handle to make the conditions easier and make handling same as original.

Issue #915: correct handling of checkstyle.ant.skip

---

.ci/checks-no-exception.sh
.ci/util.sh
.ci/validation.sh

identified from https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.ci/validation.sh#L20 when trying to run locally and running into issues,
````
sevntu.checkstyle/ $ ./.ci/validation.sh eclipse-cs
.....
fatal: destination path 'eclipse-cs' already exists and is not an empty directory.
sevntu.checkstyle/.ci-temp/eclipse-cs/ $ git status
HEAD detached at 10.0.0
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:  docs/partials/releases/5.0.0final/release_notes.html
modified:  docs/sitemap.xml
no changes added to commit (use "git add" and/or "git commit -a")
````

minor: simplify scripts and ensure we are able to rerun

---

.travis.yml
eclipse-pom.xml

This removed s390x because travis is having issues running it and also synchronizes configuration with what is found in eclipse-cs.
Comparison at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/928#issuecomment-1295942685

config: removal of s390x

---

update-site/index.html

Sentence finish should not be part of hyperlink.

doc: fix typo in hyperlink

---

README.textile

I only wrote as far back as 1.30.0 but I can do all the way back.
Generated via:
````
@echo off
call :CheckSevntu 1.10.0
call :CheckSevntu 1.11.0
call :CheckSevntu 1.12.0
call :CheckSevntu 1.13.0
call :CheckSevntu 1.13.1
call :CheckSevntu 1.13.2
call :CheckSevntu 1.13.3
call :CheckSevntu 1.13.4
call :CheckSevntu 1.13.5
call :CheckSevntu 1.13.6
call :CheckSevntu 1.14.0
call :CheckSevntu 1.15.0
call :CheckSevntu 1.16.0
call :CheckSevntu 1.16.1
call :CheckSevntu 1.17.0
call :CheckSevntu 1.17.1
call :CheckSevntu 1.18.0
call :CheckSevntu 1.19.0
call :CheckSevntu 1.19.1
call :CheckSevntu 1.19.2
call :CheckSevntu 1.20.0
call :CheckSevntu 1.21.0
call :CheckSevntu 1.21.1
call :CheckSevntu 1.22.0
call :CheckSevntu 1.23.0
call :CheckSevntu 1.23.1
call :CheckSevntu 1.24.0
call :CheckSevntu 1.24.1 …
```

minor: adds sevntu compatibility matrix

---

.github/dependabot.yml

Added to more sevntu projects. I assume eclipsecs is not possible since it is not in maven.

config: adds dependabot for sevntu idea and sevntu sonar

---

eclipsecs-sevntu-plugin-feature/feature.xml
sevntu-checks/config/checkstyle_non_main_files_suppressions.xml

Issue identified during deployment test.
````
diff --git a/eclipsecs-sevntu-plugin-feature/feature.xml b/eclipsecs-sevntu-plugin-feature/feature.xml
index 82b90d8..e718a9f 100644
--- a/eclipsecs-sevntu-plugin-feature/feature.xml
+++ b/eclipsecs-sevntu-plugin-feature/feature.xml
@@ -1,6 +1,5 @@
<?xml version="1.0" encoding="UTF-8"?>
-<feature id="com.github.sevntu.checkstyle.checks.feature"
-   label="Extension for eclipse-cs plugin with additional Checks" version="1.44.0">
+<feature id="com.github.sevntu.checkstyle.checks.feature" label="Extension for eclipse-cs plugin with additional Checks" version="1.44.1">
<description url="http://sevntu-checkstyle.github.io/sevntu.checkstyle/">
http://sevntu-checkstyle.github.io/sevntu.checkstyle/
@@ -17,15 +16,11 @@
</license>
<url>
- …
```

minor: restore features formatting and added remaining suppressions

---

sevntu-checkstyle-sonar-plugin/pom.xml

Same update as before.
I am not sure how I missed this before or how it passed on my local before when I was going through this.
I did another scan and did not find any other POMs with the old version.

config: update maven-javadoc-plugin for sonar plugin to 3.4.1

---

.github/workflows/bump_license_year.yml

Source: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
Proof of working: https://github.com/Vyom-Yadav/actions-test/commit/8ae3f4490e16f3bbba5f252f96b03e15198e8122

infra: fix bump_license_year.yml not adding year to commit message

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java

minor: make private class final with default constructor
This is part of https://github.com/checkstyle/checkstyle/pull/12737
According to the https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.8.9 The default constructor has the same access modifier as the class.
and according to the check https://checkstyle.org/config_design.html#FinalClass a class that has only private constructors and has no descendant classes is declared as final.

minor: make private class final with default constructor

---

sevntu-checks/config/ant-phase-verify.xml
sevntu-checks/pom.xml

From https://github.com/checkstyle/checkstyle/pull/12755#discussion_r1112055478
> So before mergin this PR we need 1 PR for checkstyle repo to make it as variable and 1 PR for sevnu to define this variable.
Related to https://github.com/checkstyle/checkstyle/pull/12761

Pull #990: Define variable for non-main-files-suppressions file

---

eclipsecs-sevntu-plugin/pom.xml
sevntu-checks/pom.xml
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java
sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckstyleRegressionTest.java
sevntu-checkstyle-sonar-plugin/pom.xml

Addresses https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/990#issuecomment-1454337832:
> It seems there is issues with the travis runs and it is actually failing. This PR just had a 10 minute time out run and it was not confirmed to be working. Another PR is failing.
In release 10.8.0 we renamed lots of config files to `kebab-case` and once the release was released, CI started failing because it was looking for the older names which used to be `snake_case`

Pull #995: Point to files that were renamed to be kebab-case

---

sevntu-checks/config/checkstyle-non-main-files-suppressions.xml

We are implementing a check to enforce workflow job steps are spaced out in https://github.com/checkstyle/checkstyle/pull/12900
It is better to suppress it for now and implement it when PR gets merged and 10.9.3 is out.

Pull #1002: Suppress check for keeping spacing between workflow job steps

---

sevntu-checks/config/suppressions.xml

Suppresses check that requires all message keys to have a `@MessageKey` annotation.
This blocks PR https://github.com/checkstyle/checkstyle/pull/13129
https://checkstyle.semaphoreci.com/jobs/d049f8c2-24e8-45bd-a7da-91bb44d9e113
```
[INFO] --- maven-antrun-plugin:3.1.0:run (ant-phase-verify) @ sevntu-checks ---
[INFO] Executing tasks
[INFO]      [echo] Checkstyle started (../../../config/checkstyle-checks.xml): 04/06/2023 01:21:58 PM
[INFO] [checkstyle] Running Checkstyle 10.12.1-SNAPSHOT on 141 files
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/checkstyle/.ci-temp/sevntu.checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationCheck.java:50:5: Message keys should have @MessageKey annotation [missingMessageKeyAnnotation]
[ERROR] …
```

Pull #1018: Add suppression for missingMessageKeyAnnotation

---

sevntu-checks/config/suppressions.xml

Related to #1022 
---
Adds suppression for settersHaveSinceTag because the pipeline at https://github.com/checkstyle/checkstyle/pull/13455 is failing
https://checkstyle.semaphoreci.com/jobs/b80149c4-f163-4908-a4ab-98a19bcb625e#L902
```
[ERROR] [checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/sevntu.checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java:163:5: All property setters of a module should contain a @since tag. [settersHaveSinceTag] 01:13
[ERROR] [checkstyle] [ERROR] /home/semaphore/checkstyle/.ci-temp/sevntu.checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java:255:5: All property setters of a module should contain a @since tag. [settersHaveSinceTag] 01:13 …
```

Pull #1023: Add suppression for settersHaveSinceTag

---

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/CauseParameterInExceptionCheck.java

part of: https://github.com/checkstyle/checkstyle/pull/15686
detected at: https://checkstyle.semaphoreci.com/jobs/46bc3abc-9190-43d9-bb99-3a25a47a386b#L757

minor: fixed P tag content's placement in CauseParameterInExceptionCheck.java
