sevntu-checkstyle/sevntu.checkstyle

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleStringLiteralsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/EnumValueNameCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java
- "static final" arrays should be "private"
- "for" loop incrementers should modify the variable being tested in the loop's stop condition
- Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList"
Pull #319
=> Fixed Sonar critical and major violations:

sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputUnnecessaryParentheses.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/testUBV.java
- added double parentheses for assertion test
- make sure that parentheses are checked when assertion is enabled and disabled
- removed assertion for input parameter that is already checked before function is invoked (double check)
=> Improved UnnecessaryParenthesesExtendedCheck test coverage:

sevntu-checks/pom.xml, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputUselessSingleCatchCheck5.java
=> Improved UselessSingleCatchCheck code coverage

sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheckTest.java, sevntu-checks/src/test/resources-noncompilable/com/github/sevntu/checkstyle/checks/coding/InputNumericLiteralNeedUnderscoreCheck3.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputNumericLiteralNeedUnderscoreCheck.java
=> Issue #425: New option to skip fields by regexp

sevntu-checkstyle-sonar-plugin/pom.xml
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/436
Tested on sonarqube 5.3 with project analysis.
=> Issue #436: Hotfix for sonar crash

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/annotation/RequiredParameterForAnnotationCheckTest.java
This prevented me from running the tests in the IDE. Seems someone has used the wrong `Assert` class.
=> Replace `Assert` class from internal Sun package with junit `Assert`

.gitignore
Signed-off-by: Michael Vorburger <vorburger@redhat.com>
=> .gitignore the .checkstyle file produced by the Eclipse CS plugin

.travis.yml, sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheckTest.java
updated eclipse-cs, junit, and powermock
=> config: bump multiple versions

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EitherLogOrThrowCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EmptyPublicCtorInClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidThrowAnonymousExceptionsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleStringLiteralsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ReturnCountExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/TernaryPerExpressionCountCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSingleCatchCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSuperCtorCallCheck.java, sevntu-checks/suppressions.xml
Issue #310
Starting to remove some legacy suppressions.
Mostly trying to stick to small style changes, did some minor modifications for return count check.
Added new suppressions for the more complex checks. Also for some javadocs as they require more attention, like adding placement of `<p>`.
=> Issue #310: removed some legacy violations from sevntu

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/ChecksTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/XmlUtil.java, sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml
Some of the code is from checkstyle project.
Most automation is in sonar. Very similar to checkstyle's XDoc verification.
We validate almost everything except types and default values and descriptions.
Please review changes in sonar file as I am not familiar with it.
=> started automated testing of sonar and eclipsecs files

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/FinalizeImplementationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidReturnInFinallyBlockCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NameConventionForJunit4TestClassesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SingleBreakOrContinueCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSuperCtorCallCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/BaseCheckTestSupport.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/annotation/RequiredParameterForAnnotationCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ConstructorWithoutParamsCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/naming/EnumValueNameCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/ChecksTest.java
Exceptions not thrown, override missing, methods can be static, methods not used.
=> minor: fixed eclipse errors

sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/InnerClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java
=> Issue #496: enabled ForbidCCommentsInMethods

sevntu-checks/sevntu-checks.xml
Issue #496
Didn't check them all, stopped at last one.
=> Issue #496: enabled sevntu checks with no violations

sevntu-checks/sevntu-checks.xml
Issue #496
The last of the no violation checks.
=> Issue #496: enabled more sevntu checks with no violations

sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidDefaultSerializableInInnerClassesCheck.java
=> Issue #496: enabled ReturnCountExtendedCheck

sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java
=> Issue #496: resolving SingleBreakOrContinueCheck violations

sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EitherLogOrThrowCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/InnerClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NoMainMethodInAbstractClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java
=> Issue #496: AvoidConstantAsFirstOperandInConditionCheck, ConfusingConditionCheck, LogicConditionNeedOptimizationCheck

sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationElementValueCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/RequiredParameterForAnnotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EitherLogOrThrowCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EmptyPublicCtorInClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidReturnInFinallyBlockCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidThrowAnonymousExceptionsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ReturnCountExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ReturnNullInsteadOfBooleanCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/TernaryPerExpressionCountCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/CauseParameterInExceptionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NoMainMethodInAbstractClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/ChecksTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/XmlUtil.java
Issue #496
CustomDeclarationOrderCheck.java: Static method wasn't picked up by StaticMethodCandidate until the contents of the <>s was removed.
=> Issue #496: enabled DiamondOperatorForVariableDefinition

sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleStringLiteralsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ReturnCountExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSuperCtorCallCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/EnumValueNameCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java
=> Issue #496: multiple checks

sevntu-checks/sevntu-checks.xml, sevntu-checks/sevntu-suppressions.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSuperCtorCallCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheck.java
Issue #496
I had to enable suppressions for test and some known bugs in checks.
=> Issue #496: IllegalCatchExtended and SimpleAccessorNameNotation

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CommitValidationTest.java
Issue #451
Copied test from main
=> Issue #451: added commit validation test

sevntu-checks/src/main/resources/sevntu_checks_packages.xml
=> Issue #259: added checkstyle package xml

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/UtilsTest.java
=> Issue #520: 100% coverage for Utils

sevntu-checks/pom.xml, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputFinalizeImplementationCheck.java
Issue #520
Just more test cases.
=> Issue #520: 100% coverage for FinalizeImplementationCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheckTest.java
=> Issue #520: 100% coverage for ForbidInstantiationCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/AvoidConditionInversionTest.java
=> Issue #520: 100% coverage for AvoidConditionInversionCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheckTest.java
Issue #520
Just a new test.
Renamed test file to follow the name of the check.
=> Issue #520: 100% coverage for LineLengthExtendedCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheckTest.java
=> Issue #520: 100% coverage for PublicReferenceToPrivateTypeCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/CauseParameterInExceptionCheckTest.java
=> Issue #520: 100% coverage for CauseParameterInExceptionCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ReturnNullInsteadOfBooleanCheckTest.java
=> Issue #520: 100% coverage for ReturnNullInsteadOfBooleanCheck

sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/DiamondOperatorForVariableDefinitionCheck.java
Issue #520
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/141/
Can't find an instance where result type is `TYPE_ARGUMENTS`.
=> Issue #520: 100% coverage for DiamondOperatorForVariableDefinitionCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/EmptyPublicCtorInClassCheckTest.java
=> Issue #520: 100% coverage for EmptyPublicCtorInClassCheck

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Added github MD files. Copied from checkstyle, small modifications for how sevntu is run in the CLI.
=> config: introduction of github md files

sevntu-checks/pom.xml, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputInnerClassCheck.java
=> Issue #520: 100% coverage for InnerClassCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheckTest.java
=> Issue #520: 100% coverage for RedundantReturnCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ReturnBooleanFromTernaryCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputReturnBooleanFromTernary.java
=> Issue #520: 100% coverage for ReturnBooleanFromTernaryCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/MultipleStringLiteralsExtendedCheckTest.java
=> Issue #520: 100% coverage for MultipleStringLiteralsExtendedCheck

sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheck.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputMultipleVariableDeclarations.java
Issue #520 
`!inClass` was removed because we are already checking `inClass` above in same if/else chain.
1 new test added.
=> Issue #520: 100% coverage for MultipleVariableDeclarationsExtendedCheck

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/NameConventionForJunit4TestClassesCheckTest.java
=> Issue #520: 100% coverage for NameConventionForJunit4TestClassesCheck

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidThrowAnonymousExceptionsCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/AvoidConditionInversionCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/naming/InterfaceTypeParameterNameCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/AllChecksTest.java
Issue #551 - Item 2
All checks must now have test that match check name + "Test" and be located in the same package as the check is.
=> Issue #551: verify checks have tests

sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/EnumValueNameCheck.java
=> Issue #520: 100% coverage for EnumValueNameCheck

.github/ISSUE_TEMPLATE.md
=> Issue #560: changed issue template to specify command based on OS

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidNotShortCircuitOperatorsForBooleanCheckNonClasses.java
=> Issue #568: fixed NPE in non-classes for ShortCircuitOperators check

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputMapIterationInForEachLoopCheckExtendingMap.java
=> Issue #427: fixed NPE in MapIterationInForEachLoopCheck for map classes

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputNoNullForCollectionReturnCheckConstructor.java
=> Issue #573: fixed NPE in NoNullForCollectionReturnCheck for constructors

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputMapIterationInForEachLoopCheckExtendingMap.java
=> Issue #580: fixed NPE in MapIterationInForEachLoop for maps without this

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/FinalizeImplementationCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/FinalizeImplementationCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputFinalizeImplementationCheckSpecial.java
=> Issue #578: fixed NPE in FinalizeImplementationCheck

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidHidingCauseExceptionCheckWrapping.java
=> Issue #577: fixed NPE in AvoidHidingCauseException on wrapping

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/naming/checkstyle-metadata.properties, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/naming/checkstyle-metadata.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/EnumValueNameCheck.java, sevntu-checks/src/main/resources/com/github/sevntu/checkstyle/checks/naming/messages.properties, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/naming/EnumValueNameCheckTest.java, sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml
Issue #448
This may cause issues on CI regression to main project since we are removing properties in the rewrite and checkstyle is already using it.
=> Issue #448: rewrote EnumValueNameCheck to follow naming check pattern

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheckTest.java
Fix for https://github.com/checkstyle/checkstyle/pull/4767
Will rename commit once I get a PR number.
=> PR #: removed excess hierarchy from IllegalCatchExtendedCheck

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java
Fix for PR https://github.com/checkstyle/checkstyle/pull/4736 and Issue https://github.com/checkstyle/checkstyle/issues/4727.
=> Pull #601: fixed missing final from bug in FinalLocalVariableCheck

sevntu-checks/suppressions.xml
=> Issue #525: removed unnecessary suppressions

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EmptyPublicCtorInClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/FinalizeImplementationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidReturnInFinallyBlockCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleStringLiteralsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NameConventionForJunit4TestClassesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/BaseCheckTestSupport.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/XmlUtil.java, sevntu-checks/suppressions.xml
=> Issue #525: removed return count suppression and fixed violations

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/package-info.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/package-info.java, sevntu-checks/suppressions.xml
=> Issue #525: removed javadoc package suppression and fixed violations

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java, sevntu-checks/suppressions.xml
=> Issue #525: removed boolean complexity suppression and fixed violations

.travis.yml, sevntu-checks/.ci/eclipse-compiler-javac.sh, sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCCommentsInMethodsCheck.java
=> Issue #616: add eclipse violation check as a maven plugin

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/suppressions.xml
=> Issue #525: removed modified control suppression and fixed violations

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.properties, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.xml, sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheck.java, sevntu-checks/src/main/resources/com/github/sevntu/checkstyle/checks/coding/messages.properties, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/BaseCheckTestSupport.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/UtilsTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/EmptyPublicCtorInClassCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ReturnNullInsteadOfBooleanCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/AvoidConditionInversionCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/CauseParameterInExceptionCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ConstructorWithoutParamsCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck1.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck2.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck3.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck4.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck5.java, sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml
Issue #618
I expect this to fail as changes need to be made to the main project and I need to update the XML files for this check.
=> Issue #618: added RequireFailForTryCatchInJunitCheck

sevntu-checkstyle-default-configuration.xml
=> Issue #610: added CheckstyleTestMakeupCheck to default configuration

sevntu-checks/checkstyle.properties
From [issue 4421](https://github.com/checkstyle/checkstyle/pull/5390#issuecomment-353926532)
=> minor: add property, the path to future xpath-suppressions config file

.travis.yml
Added `-e` to all maven command just like https://github.com/checkstyle/checkstyle/pull/5408 .
=> minor: add '-e' to all mvn executions

.ci/travis.sh, .travis.yml, eclipsecs-sevntu-plugin/pom.xml, sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputForbidCertainImportsCheck.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputForbidCertainImportsCheckSinglePackage.java, sevntu-checkstyle-sonar-plugin/checkstyle.properties, sevntu-checkstyle-sonar-plugin/pom.xml
=> Issue #629: upgrade to eclipse-cs of 8.7

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.properties, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.xml, sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheck.java, sevntu-checks/src/main/resources/com/github/sevntu/checkstyle/checks/coding/messages.properties, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputForbidCertainMethodCheck.java, sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml
Issue #604
continuation of PR #605
reports:
https://raghavgautam.github.io/halt/
https://raghavgautam.github.io/assert/
https://raghavgautam.github.io/exit/
=> Issue #604: Add a check to ban use of specified method

.travis.yml
This is for gh-pages only.
Based on conversations from https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/646#issuecomment-369035793 .
=> added blank travis file

sevntu-checks/sevntu-checks.xml
Issue #648: Updating sevntu-checks.xml to refer to new dtd
=> Issue #648: Updating sevntu-checks.xml to refer to new dtd

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/annotation/checkstyle-metadata.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/design/checkstyle-metadata.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/naming/checkstyle-metadata.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/sizes/checkstyle-metadata.xml
`$ curl -v https://checkstyle.github.io/eclipse-cs/dtds/checkstyle-metadata_1_1.dtd 2>&1|grep Loc`
```
< Location: http://checkstyle.org/eclipse-cs/dtds/checkstyle-metadata_1_1.dtd
```
=> minor: follow redirect

.github/PULL_REQUEST_TEMPLATE.md, README.textile, deploy.sh, pom-version-bump.sh, sevntu-checks/import-control.xml, sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationElementValueCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EmptyPublicCtorInClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/FinalizeImplementationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidReturnInFinallyBlockCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidThrowAnonymousExceptionsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSingleCatchCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSuperCtorCallCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/CheckstyleTestMakeupCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheck.java, sevntu-checks/src/main/sh/ast.sh, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputHideUtilityClassConstructorCheck4.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/sizes/InputLineLengthExtendedCheck.java, sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`
split from #651
=> spelling: comments

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ConfusingConditionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EitherLogOrThrowCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationElementValueCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidDefaultSerializableInInnerClassesCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/AllChecksTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/ChecksTest.java, sevntu-checks/src/test/resources-noncompilable/com/github/sevntu/checkstyle/checks/coding/InputRedundantReturnCheckTestNPE.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidDefaultSerializableInInnerClassesCheck1.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidHidingCauseExceptionCheck.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputCustomDeclarationOrderCheck.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputOverridableMethodInConstructorCheck27.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputForbidWildcardAsReturnTypeCheck.java
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`
split from #651
=> spelling: functions/variables

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/WhitespaceBeforeArrayInitializerCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/HideUtilityClassConstructorCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/InnerClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheck.java
=> Issue #662: moved easy Checks to log AST

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheckTest.java
=> Issue #662: moved line only Checks to log AST (part 3)

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleStringLiteralsExtendedCheck.java
=> Issue #662: moved MultipleStringLiteralsExtendedCheck to log AST

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidConstantAsFirstOperandInConditionCheck.java
=> Issue #672: added all condition operands to AvoidConstantAsFirst

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputAvoidNotShortCircuitOperatorsForBooleanCheckLambdaWithMultiCatch.java
Issue #659 
Issue is not yet approved, but I verified the issue.
=> Issue #659: fixed AvoidNotShortCircuitOperatorsForBoolean multi-catch

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputLogicConditionNeedOptimizationCheck.java
=> Issue #661: ignore instanceof in LogicConditionNeedOptimizationCheck

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputLogicConditionNeedOptimizationCheck.java
Issue #683
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/171/
All are false positives being removed.
=> Issue #683: fixed parenthesis handling in LogicConditionNeedOptimization

wercker.yml
Adding base of wercker configuration to ensure sevntu will compile and travis will be skipped.
=> config: added base of wercker yml

.ci/travis.sh, .travis.yml
=> Issue #691: added verification of contribution checks-sevntu-error.xml

sevntu-checks/.ci/wercker.sh, wercker.yml
=> Issue #644: added no exception testing to wercker

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/TernaryPerExpressionCountCheck.java, sevntu-checks/suppressions.xml
=> Issue #525: removed javadoc variable suppression and fixed violations

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EitherLogOrThrowCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/EmptyPublicCtorInClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidThrowAnonymousExceptionsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NameConventionForJunit4TestClassesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NoNullForCollectionReturnCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/TernaryPerExpressionCountCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UselessSuperCtorCallCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/WhitespaceBeforeArrayInitializerCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NestedSwitchCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheck.java, sevntu-checks/suppressions.xml
=> Issue #525: removed javadoc paragraph suppression and fixed violations

.ci/travis.sh, eclipsecs-sevntu-plugin/pom.xml
=> Issue #658: upgrade to eclipse-cs 8.10

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheck.java, sevntu-checks/suppressions.xml
=> Issue #525: removed npath complexity suppression and fixed violations

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java, sevntu-checks/suppressions.xml
=> Issue #525: removed inner assignment suppression and fixed violations

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java, sevntu-checks/suppressions.xml
=> Issue #525: removed some UnnecessaryParenthesesExtendedCheck violations

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRedundantReturnCheckNestedMethods.java
=> Issue #650: skip over object blocks in RedundantReturnCheck

.ci/travis.sh, deploy-all.sh, deploy.sh, release.sh, sevntu-checks/pom.xml, sevntu-checkstyle-idea-extension/pom.xml, sevntu-checkstyle-maven-plugin/pom.xml, sevntu-checkstyle-sonar-plugin/pom.xml, sevntu_xdoc_freemarker.template, update-site/pom.xml
=> Issue #638: added release script

.ci/travis.sh, eclipsecs-sevntu-plugin/pom.xml, sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/Utils.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MoveVariableInsideIfCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleStringLiteralsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleVariableDeclarationsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/CheckstyleTestMakeupCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ConstructorWithoutParamsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/MapIterationInForEachLoopCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/MoveVariableInsideIfCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/NestedSwitchCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputStaticMethodCandidateCheck.java
=> Issue #712: upgrade to eclipse-cs 8.11

.ci/travis.sh, eclipsecs-sevntu-plugin/pom.xml, sevntu-checks/pom.xml
=> Issue #716: upgrade to eclipse-cs 8.12.0

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckstyleRegressionTest.java
=> Issue #718: fixed regression line length for dynamic modules added

sevntu-checks/pom.xml, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/TernaryPerExpressionCountCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheckTest.java, sevntu-checkstyle-sonar-plugin/pom.xml, sevntu-checkstyle-sonar-plugin/suppressions.xml
=> Issue #729: upgrade to checkstyle and eclipse-cs 8.18

.travis.yml, sevntu-checks/.ci/eclipse-compiler-javac.sh
=> Issue #733: re-enable and fix eclipse-compiler

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/DiamondOperatorForVariableDefinitionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidCCommentsInMethodsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ForbidWildcardAsReturnTypeCheck.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputDiamondOperatorForVariableDefinitionCheck.java
=> Issue #743: fix compiling issues with checkstyle 8.21

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/annotation/checkstyle-metadata.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/design/checkstyle-metadata.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/naming/checkstyle-metadata.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/sizes/checkstyle-metadata.xml
=> Issue #749: fix URL in xml files to https

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/Jsr305AnnotationsCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/Jsr305AnnotationsCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputJsr305AnnotationsCheckWithNestedAnnotation.java
This fixes the issue from #751.
=> Issue #751: Jsr305AnnotationsCheck is crashing on checkstyle sources

.ci/travis.sh
=> config: fix sevntu regression

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/AllChecksTest.java
Fix from reg report in https://github.com/checkstyle/checkstyle/pull/6846
=> minor: change lambda to method reference

.ci/travis.sh, eclipsecs-sevntu-plugin/pom.xml
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/9765a3bf0f02272f921aec264667328f2ca60339/sevntu-checks/pom.xml#L19
=> minor: sync eclipse-cs to 8.18

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputSimpleAccessorNameNotationCheckOverride.java
=> Issue #777: ignore override method for SimpleAccessorNameNotation

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidNotShortCircuitOperatorsForBooleanCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java
Issue https://github.com/checkstyle/checkstyle/issues/6724
=> minor: format sources for JavadocSummaryLocation

sevntu-checks/pom.xml
=> Issue #785: use latest checkstyle version in verify phase

sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck6.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck7.java
Issue #789
Support for Junit5 tests
=> Issue #789: Support Junit5 in RequireFailForTryCatchInJunit

.ci/travis.sh, .gitignore, .travis.yml, eclipsecs-sevntu-plugin/pom.xml, sevntu-checks/pom.xml
=> 795 eclipse cs 8.28.0 4

sevntu-checks/pom.xml
Upgrade checkstyle verification version only.
=> config: upgrade checkstyle verify to 8.30

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidDefaultSerializableInInnerClassesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java
https://github.com/checkstyle/checkstyle/pull/7775
=> minor: fix violations from JavadocMissingWhitespaceAfterLeadingAsteriskCheck

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/RequiredParameterForAnnotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidDefaultSerializableInInnerClassesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidThrowAnonymousExceptionsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/Jsr305AnnotationsCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/OverridableMethodInConstructorCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheck.java
As discussed in https://github.com/checkstyle/checkstyle/pull/8013#issuecomment-610248687
=> minor: fix violations for RedundantThisCheck

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java
PR to fix failing CI in https://github.com/checkstyle/checkstyle/pull/8213.
These are internal Checkstyle violations that were previously not detected due to issue https://github.com/checkstyle/checkstyle/issues/8117.
I'm not familiar with contribution to this repo, so if I'm missing any sort of regression or test report feel free to let me know.
=> minor: fix violations from JavadocMethod

eclipsecs-sevntu-plugin/pom.xml, eclipsecs-sevntu-plugin/src/com/github/sevntu/eclipse-metadata.yml
#822 
Details are mentioned in the issue
=> Issue #822: Introduction of YML metadata for eclipse-cs integration

sevntu-checks/pom.xml, sevntu-checks/sevntu-checks.xml
configuration fixes that detected at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/827#issuecomment-779511172
=> Ci update cs version

sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck1.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck10.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputRequireFailForTryCatchInJunitCheck11.java
=> Issue #826: Support AssertJ/Google Truth fail() methods in RequireFailForTryCatchInJunitCheck

eclipsecs-sevntu-plugin/src/checkstyle_packages.xml, sevntu-checks/sevntu-checks.xml, sevntu-checks/sevntu-suppressions.xml, sevntu-checks/src/main/resources/checkstyle_packages.xml, sevntu-checks/suppressions.xml, sevntu-checkstyle-sonar-plugin/suppressions.xml
Updated all DOCTYPEs for our XML files.
=> minor: update all doctypes for checkstyle xml files

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidHidingCauseExceptionCheck.java
https://github.com/checkstyle/checkstyle/pull/9744#issuecomment-808970415
=> minor: Fixed violations for JavadocTagContinuationIndentation

.ci/travis.sh
=> Issue #836: skip xml validation in sub build of checkstyle

eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.properties, eclipsecs-sevntu-plugin/src/com/github/sevntu/checkstyle/checks/coding/checkstyle-metadata.xml, sevntu-checks/sevntu-checks.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/PreferMethodReferenceCheck.java, sevntu-checks/src/main/resources/com/github/sevntu/checkstyle/checks/coding/messages.properties, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/PreferMethodReferenceCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputPreferMethodReferenceCheck1.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputPreferMethodReferenceCheck2.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputPreferMethodReferenceCheck3.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/coding/InputPreferMethodReferenceCheck4.java, sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml, sevntu-checkstyle-sonar-plugin/src/test/java/com/github/sevntu/checkstyle/sonar/CheckstyleExtensionRulesDefinitionTest.java
Resolves Issue #825: New Check "Prefer method reference to lambda"
Files not added from original :
1. [whitelist.words](https://github.com/strkkk/checkstyle/blob/83182af23e9012993a10218adcb46eadce72ef41/.ci/jsoref-spellchecker/whitelist.words)
2. [XpathRegressionPreferMethodReferenceTest.java](https://github.com/strkkk/checkstyle/blob/83182af23e9012993a10218adcb46eadce72ef41/src/it/java/org/checkstyle/suppressionxpathfilter/XpathRegressionPreferMethodReferenceTest.java)
3. [SuppressionXpathRegressionPreferMethodReference.java](https://github.com/strkkk/checkstyle/blob/83182af23e9012993a10218adcb46eadce72ef41/src/it/resources/org/checkstyle/suppressionxpathfilter/prefermethodreference/SuppressionXpathRegressionPreferMethodReference.java)
4. …
=> Issue #825: Add PreferMethodReferenceCheck

sevntu-checks/suppressions.xml
As discussed from https://github.com/checkstyle/checkstyle/pull/9909#issuecomment-824830470
=> config: set suppression for noUsageOfGetFileContents()Method

sevntu-checks/suppressions.xml
related to new violations at https://github.com/checkstyle/checkstyle/pull/9939
=> infra: add suppressions related to checkstyle#9936

eclipsecs-sevntu-plugin/pom.xml, sevntu-checks/pom.xml
https://github.com/checkstyle/eclipse-cs/tags
Eclipse-CS is on 8.40 .
=> config: update eclipse-cs dependency to 8.40.0

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/ReturnCountExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java
Contribution PR: https://github.com/checkstyle/checkstyle/pull/9699
https://github.com/checkstyle/checkstyle/pull/9699#issuecomment-826819142
=> Issue #8990: JavadocParamOrder Checkstyle check

sevntu-checks/.ci/eclipse-compiler-javac.sh
Matching Checkstyle PRs:
https://github.com/checkstyle/checkstyle/pull/10128
https://github.com/checkstyle/checkstyle/pull/10139
=> infra: bump eclipse compiler to R4.20

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputStaticMethodCandidateCheckTypeParameter.java
Related to https://github.com/checkstyle/checkstyle/pull/10122
https://nmancus1.github.io/issue-10121_check_diff_reports_2021_06_16/diff_sevntu-check-regression_part_1/index.html
Regression in `StaticMethodCandidate`
https://nmancus1.github.io/issue-10121_check_diff_reports_2021_06_16/diff_sevntu-check-regression_part_2/index.html
Clean
------------------------------
https://nmancus1.github.io/issue-10121_check_diff_reports_2021_06_16/diff_sevntu-check-regression_part_1_post_PR854/index.html
Clean
https://nmancus1.github.io/issue-10121_check_diff_reports_2021_06_16/diff_sevntu-check-regression_part_2_post_PR854/index.html
Clean
-------------------
=> minor: update StaticMethodCandidateCheck (related to checkstyle#10121)

eclipsecs-sevntu-plugin/pom.xml
requirements for breaking activity in checkstyle before 9.0
=> config: bump eclipse-cs to 8.44.0-SNAPSHOT

index.html
minor: The incorrect date makes this extension seem abandoned. Especially with the fact I can't access the update site to install the latest version
=> minor: Update index.html

wercker.yml
remove all skip logic as it is not reliable and project is not that active
=> infra: activate wercker execution

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java
=> Issue #873: add missing javadoc

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidDefaultSerializableInInnerClassesCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/InnerClassCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java
Related to https://github.com/checkstyle/checkstyle/pull/10574.
Regressions discovered in following reports:
https://nmancus1.github.io/issue-3095-b_check_diff_reports_2021_08_08/diff_sevntu-check-regression_part_1/index.html
https://nmancus1.github.io/issue-3095-b_check_diff_reports_2021_08_08/diff_sevntu-check-regression_part_2/index.html
Before merging this PR:
1. Checkstyle must release changes in https://github.com/checkstyle/checkstyle/pull/10574 (9.0)
2. The version of checkstyle in sevntu must update to the new eclipse-cs version 9.0
=> minor: update checks (related to checkstyle#3095)

sevntu-checkstyle-sonar-plugin/src/main/resources/com/github/sevntu/checkstyle/sonar/checkstyle-extensions.xml
=> minor: Fix usage of tags inside description field to fix parsing problem with Sonarqube 9.x

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/annotation/ForbidAnnotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/IllegalCatchExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/SimpleAccessorNameNotationCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/TernaryPerExpressionCountCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/UnnecessaryParenthesesExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/ChecksTest.java
Related to https://github.com/checkstyle/checkstyle/issues/11522, noticed at https://app.travis-ci.com/github/checkstyle/checkstyle/jobs/566540188
=> minor: renaming to comply with new config rules in main repo

.travis.yml, eclipse-pom.xml, eclipsecs-sevntu-plugin/pom.xml, sevntu-checks/import-control.xml, sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/MultipleStringLiteralsExtendedCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/AvoidConditionInversionCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/ChildBlockLengthCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheck.java, wercker.yml
Issue #883 
Some Guava code replaced with JDK alternatives.
=> Issue #883: upgrade minimal required jdk version to 11

.ci/bump-license-year.sh, .github/workflows/bump_license_year.yml
=> Issue #891: automate execution by Github action bump-license-year.sh

.github/workflows/bump-cs-version.yml
=>  Issue #634: satelite projects should use latest checkstyle as soon at is appears in maven repo

.ci/bump-cs-version-in-sonar-plugin.sh
=> Issue #893: satelite projects should use latest checkstyle as soon at is appears in maven repo

.github/workflows/bump-cs-version.yml
=> Issue #897: Disable execution in bump project version action

sevntu-checks/.ci/eclipse-compiler-javac.sh, sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java
Issue #883
Extra updates to SH were copied from main repo.
=> Issue #883: completed upgrade to java 11

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/CheckstyleTestMakeupCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/CheckstyleTestMakeupCheckTest.java, sevntu-checks/src/test/resources/com/github/sevntu/checkstyle/checks/design/InputCheckstyleTestMakeupCheckValid.java
=> Issue #901: support add property to CheckstyleTestMakeupCheck

.ci/validation.sh
=> Issue #519: optimizes travis some

.ci/validation.sh, sevntu-checks/ant-phase-verify-sevntu.xml, sevntu-checks/ant-phase-verify.xml, sevntu-checks/checkstyle.properties, sevntu-checks/pom.xml
=> Issue #915: convert maven-checkstyle-plugin to ant

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/PreferMethodReferenceCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/NumericLiteralNeedsUnderscoreCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/PreferMethodReferenceCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/StaticMethodCandidateCheckTest.java, sevntu-checks/src/test/resources-noncompilable/com/github/sevntu/checkstyle/checks/coding/InputPreferMethodReferenceCheck5.java
=> Issue #918: fixes NPE from switch expression for PreferMethodReference

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/LogicConditionNeedOptimizationCheckTest.java, sevntu-checks/src/test/resources-noncompilable/com/github/sevntu/checkstyle/checks/coding/InputLogicConditionNeedOptimizationCheck2.java
Issue #922
I am not confident if this change is fully correct. Regression is coming.
=> Issue #922: fixes NPE from pattern definition for LogicNeedOptimization

.ci/checks-no-exception.sh, .github/workflows/checks-no-exception-workflow.yml
Adds checkstyle to no exception. It usually has tons of unique input files that can tell us how good our checks are.
Expected to fail until other PRs are merged.
=> config: adds checkstyle to no exception check

eclipse-pom.xml, eclipsecs-sevntu-plugin/pom.xml, sevntu-checks/pom.xml, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/Jsr305AnnotationsCheck.java, sevntu-checkstyle-sonar-plugin/pom.xml
=> Issue #930: upgrade to checkstyle 10.4

.ci/bump-cs-version-in-esclipsecs-plugin.sh, .ci/bump-cs-version-in-sonar-plugin.sh, .github/workflows/bump-cs-version.yml
Resolves #936 
---
Any ideas why this is failing? What am I missing here?
```
✔ ~/Open Source/sevntu.checkstyle/eclipsecs-sevntu-plugin [issue/936-fix-bump-cs-version-missed-eclipsecs-sevntu-plugin L|✔] 
21:43 $ mvn clean package
```
```
[INFO] Scanning for projects...
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2020-09/ (122B)
[INFO] Adding repository https://download.eclipse.org/releases/2020-09
[INFO] Fetching p2.index from …
```
=> Issue #936: bump-cs-version missed eclipsecs-sevntu-plugin

release.sh, sevntu-checks/config/checkstyle_non_main_files_suppressions.xml
Identified at https://github.com/checkstyle/checkstyle/pull/12499#issuecomment-1336257755
=> minor: suppressions from newest version of checkstyle

sevntu-checkstyle-idea-extension/pom.xml
Haven't tested, but this is the likely issue.
=> infra: corrects source deployment for idea-extension

sevntu_xdoc_freemarker.template
Adds date and removes extra blank line on end.
=> minor: add date to xdoc template

sevntu_xdoc_freemarker.template
Removes tabs from the template.
=> minor: removes tabs from the xdoc template

sevntu-checks/config/import-control-test.xml, sevntu-checkstyle-sonar-plugin/import-control-test.xml, sevntu-checkstyle-sonar-plugin/import-control.xml
same as https://github.com/checkstyle/contribution/issues/741
```
~/java/github/sevntu-checkstyle/sevntu.checkstyle [minor-dtd L|✔] 
$ ag "Puppy Crawl"
✘-1 
```
=> minor: use names dtd references

.ci/sonar-break-build.sh, .ci/validation.sh, .circleci/config.yml
migrates travis jobs to CircleCI
=> infra: migrate to CircleCI

.github/workflows/bump-cs-version.yml, .github/workflows/bump-license-year.yml, .github/workflows/checks-no-exception-workflow.yml, sevntu-checks/config/checkstyle-non-main-files-suppressions.xml
Resolves #1003 
---
Failures before fix:
```
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/sevntu.checkstyle/.github/workflows/bump-cs-version.yml:22: Workflow job steps should have empty lines between each other [workflowJobStepSpacing]
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/sevntu.checkstyle/.github/workflows/bump-cs-version.yml:28: Workflow job steps should have empty lines between each other [workflowJobStepSpacing]
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/sevntu.checkstyle/.github/workflows/bump-cs-version.yml:33: Workflow job steps should have empty lines between each other [workflowJobStepSpacing]
[ERROR] [checkstyle] [ERROR] /home/stoyan/open-source/sevntu.checkstyle/.github/workflows/bump-license-year.yml:20: Workflow job steps should have …
```
=> Issue #1003: Update workflow job steps spacing

sevntu-checks/config/ant-phase-verify.xml, sevntu-checks/pom.xml
part of https://github.com/checkstyle/checkstyle/pull/15376
=> minor: define the new property in pom.xml and transfer it to ant run

sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/CustomDeclarationOrderCheck.java, sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheck.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/SevntuUtilTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/AvoidModifiersForTypesCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/EmptyPublicCtorInClassCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainImportsCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidCertainMethodCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ForbidInstantiationCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RedundantReturnCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/RequireFailForTryCatchInJunitCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/ReturnNullInsteadOfBooleanCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/coding/TernaryPerExpressionCountCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/AvoidConditionInversionCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/CauseParameterInExceptionCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/CheckstyleTestMakeupCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/design/PublicReferenceToPrivateTypeCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/naming/UniformEnumConstantNameCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/checks/sizes/LineLengthExtendedCheckTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/AllChecksTest.java, sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/CheckUtil.java
=> Issue #1041: Rename CatchParameterName in sevntu-checks

sevntu-checks/src/test/java/com/github/sevntu/checkstyle/internal/ChecksTest.java
From https://github.com/checkstyle/checkstyle/pull/17181
=> supplemental: update indentation of new's child

.circleci/config.yml, .github/workflows/checks-no-exception-workflow.yml, eclipsecs-sevntu-plugin/pom.xml, sevntu-checks/pom.xml, sevntu-checkstyle-idea-extension/pom.xml, sevntu-checkstyle-sonar-plugin/checkstyle.properties, sevntu-checkstyle-sonar-plugin/pom.xml
=> Issue #1039: Migrate Project to jdk17
